//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class F_ExtensionCardHelpWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(F_ExtensionCardHelp), typeof(System.Object));
		L.RegFunction("Extension", Extension);
		L.RegFunction("ConversionCard", ConversionCard);
		L.RegFunction("New", _CreateF_ExtensionCardHelp);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateF_ExtensionCardHelp(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				F_ExtensionCardHelp obj = new F_ExtensionCardHelp();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: F_ExtensionCardHelp.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Extension(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			F_ExtensionCardHelp.Extension(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ConversionCard(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			object arg0 = ToLua.ToVarObject(L, 1);
			F_ExtensionCard o = F_ExtensionCardHelp.ConversionCard(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

