//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class F_LoaderWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(F_Loader), typeof(FairyGUI.GLoader));
		L.RegFunction("New", _CreateF_Loader);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateF_Loader(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				F_Loader obj = new F_Loader();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: F_Loader.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

