//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class F_UnityAndroidMsgWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(F_UnityAndroidMsg), typeof(F_Singleton<F_UnityAndroidMsg>));
		L.RegFunction("Run", Run);
		L.RegFunction("OnRequestWxLogin", OnRequestWxLogin);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Run(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			F_UnityAndroidMsg obj = (F_UnityAndroidMsg)ToLua.CheckObject<F_UnityAndroidMsg>(L, 1);
			obj.Run();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnRequestWxLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			F_UnityAndroidMsg obj = (F_UnityAndroidMsg)ToLua.CheckObject<F_UnityAndroidMsg>(L, 1);
			obj.OnRequestWxLogin();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

